#homebrewを最新版にアップデート
update || true

#Formulaを更新
upgrade || true

# Add Repository
tap homebrew/versions    || true
tap phinze/homebrew-cask || true
tap homebrew/binary      || true
tap thoughtbot/formulae  || true

# パッケージのインストール
install subversion || true

## Git
install git   || true
install hub   || true
install gitsh || true
install gist  || true
install tig   || true
install gibo  || true

## Utils
install wget      || true
install curl      || true
install tree      || true
install openssl   || true
install libyaml   || true
install readline  || true
install tmux      || true
install markdown  || true
install nkf       || true
install ag        || true
install python    || true

## Image
install imagemagick    || true
install graphicsmagick || true

# Casks
install brew-cask
cask install adobe-creative-cloud || true
cask install alfred               || true
cask install chromecast           || true
cask install dash                 || true
cask install dropbox              || true
cask install google-chrome        || true
cask install google-japanese-ime  || true
cask install hipchat              || true
cask install iterm2               || true
cask install keyremap4macbook     || true
cask install marsedit             || true
cask install skitch               || true
cask install skype                || true
cask install sourcetree           || true
cask install sublime-text         || true
cask install tunnelblick          || true
cask install vagrant              || true
cask install virtualbox           || true

# Remove outdated versions
cleanup
